### ISSUE TITLE
Organization in HTML

### ISSUE THREAD

**Issue by aubreywullschleger** [dtw/prj-rev-bwfs-dasmoto#1]
Simplify! Your project is looking really great. :) in the HTML I would consider wrapping the different sections inside their own divs to make your code more organized and easy to read, like this:
```
<div>
        <h2 id="brushes">Brushes</h2>
        <img src="./resources/images/hacksaw.jpeg">
        <h3>Hacksaw Brushes</h3>
        <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <span class="price bold">Starting at $3.00 / brush.</span></p>
</div>
```
In your HTML lines 10-13 could be wrapped, 14-17 wrapped, and 18-21 wrapped. 
https://github.com/dtw/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L10-L13
https://github.com/dtw/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L14-L17
https://github.com/dtw/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L18-L21

**Comment by dtw** [comment]
How's that @aubreywullschleger ?
